language: python
python:
  - "3.5"
env:
  - DJANGO=1.10.2
install:
  - pip install -q -r requirements.txt
  - pip install -q Django==$DJANGO
  - pip install pep8
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --exclude=migrations ."
  - pyflakes -x W src
script:
  - python setup.py test
