# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('fee', models.IntegerField()),
                ('instructions_url', models.CharField(max_length=200)),
                ('langlong', models.CharField(max_length=50)),
            ],
        ),
    ]
