# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matsogi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matsogi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Level')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee', models.BooleanField(verbose_name=False)),
                ('coach', models.BooleanField(verbose_name=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Competition')),
                ('matsogi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Matsogi')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Tull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tull', models.CharField(max_length=50)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Sex')),
            ],
        ),
        migrations.CreateModel(
            name='Wirok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wirok', models.CharField(max_length=50)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Sex')),
            ],
        ),
        migrations.AddField(
            model_name='membercompetition',
            name='tki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Tki'),
        ),
        migrations.AddField(
            model_name='membercompetition',
            name='tull',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Tull'),
        ),
        migrations.AddField(
            model_name='membercompetition',
            name='wirok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Wirok'),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Sex'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Team'),
        ),
        migrations.AddField(
            model_name='matsogi',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taekwondo.Sex'),
        ),
    ]
