# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0003_auto_20161016_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tki',
            old_name='name',
            new_name='tki',
        ),
    ]
