# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0004_auto_20161016_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='name',
        ),
    ]
