# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0006_auto_20161016_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matsogi',
            old_name='matsogi',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tki',
            old_name='tki',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tull',
            old_name='tull',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wirok',
            old_name='wirok',
            new_name='name',
        ),
    ]
