# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taekwondo', '0008_auto_20161016_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercompetition',
            name='trainee',
            field=models.BooleanField(),
        ),
    ]
